version: 3

services:
    mysql:
        image: percona/percona-server:5.7
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop_cms
            MYSQL_USER: shop_cms
            MYSQL_PASSWORD: shop_cms
    php:
        container_name: shop_cms_php
        build: ./docker/php
        volumes:
            - ./:/var/www/shop_cms
        links:
            - mysql
    nginx:
        container_name: shop_cms_nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/shop_cms.conf:/etc/nginx/conf.d/default.conf